# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build and release packages

on:
  workflow_dispatch:
  schedule:
    # Runs at 05:00 AM UTC, which is 9:00 PM PST (UTC-8) / 10:00 PM PDT (UTC-7)
    # This lines up with https://github.com/iree-org/iree/blob/main/.github/workflows/schedule_candidate_release.yml
    # Downstream projects using nightly releases should expect IREE and
    # wave packages to all be available around the same time. This
    # build is much faster than the IREE build though.
    - cron: '0 5 * * *'

jobs:
  build_packages:
    if: ${{ github.repository_owner == 'iree-org' || github.event_name != 'schedule' }}
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    env:
      OUTPUT_DIR: "${{ github.workspace }}/bindist"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux packages
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp310
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp311
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp312
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp313
            platform: manylinux_x86_64

          # Windows packages.
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp310
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp311
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp312
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp313
            platform: win_amd64

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build wheels
        uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c # v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python-version }}-${{ matrix.platform }}
          CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

      - name: Upload python wheels
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          if-no-files-found: error
          name: snapshot-${{ matrix.package }}-${{ matrix.python-version }}-${{ matrix.platform }}
          path: ./wheelhouse/*.whl

  release_packages:
    needs: build_packages
    if: ${{ success() && (github.repository_owner == 'iree-org' || github.event_name != 'schedule') }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Create/update a release
    steps:
      - name: Download wheels
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: snapshot-*
          # Merge all artifacts into a single directory
          merge-multiple: true
          path: dist

      - name: Release python wheels
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifacts: dist/*.whl
          tag: "dev-wheels"
          name: "dev-wheels"
          body: "Automatic nightly release of wave-lang python wheels."
          removeArtifacts: true
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: false
