# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: "Wave GPU CI (mi35x)"

on:
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize, ready, ready_for_review, converted_to_draft]
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: "${{ matrix.os }} :: ${{ matrix.version }} :: Unit Tests and Type Checking"
    strategy:
      fail-fast: false
      matrix:
        version: [3.11]
        os: [linux-mi35x-1gpu-ossci-iree-org]
    runs-on: ${{matrix.os}}
    timeout-minutes: 60
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    container:
      image: 'ghcr.io/rocm/no_rocm_image_ubuntu24_04@sha256:405945a40deaff9db90b9839c0f41d4cba4a383c1a7459b28627047bf6302a26'
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env-file /etc/podinfo/gha-gpu-isolation-settings

    defaults:
      run:
        shell: bash

    env:
      VENV_DIR: ${{ github.workspace }}/.wave-venv
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{3.11}}
      - name: Create Python venv
        run: |
           python -m venv ${VENV_DIR}
           source ${VENV_DIR}/bin/activate

      - name: Install Rust via rustup.sh
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "CARGO_HOME=$HOME/.cargo" >> $GITHUB_ENV
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install pip deps
        if: ${{ !cancelled() }}
        run: |
          # Install TheRock
          sudo apt-get update
          sudo apt install -y gfortran build-essential binutils
          python -m pip install \
            --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx950-dcgpu/ \
            rocm[libraries,devel]
          python -m pip install \
            --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
            torch torchaudio torchvision

          # Set environment variables
          export ROCM_PATH=$(python -m rocm_sdk path --root)
          export LD_LIBRARY_PATH="$ROCM_PATH/lib":$LD_LIBRARY_PATH
          echo "ROCM_PATH=$ROCM_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV

          # Install wave deps
          python -m pip install --no-compile --upgrade pip
          pip install --no-cache-dir -r requirements-iree-pinned.txt --upgrade
          pip install -r requirements.txt -e .

      - name: Run unit tests
        if: ${{ !cancelled() }}
        run: |
          pytest -n 4 --capture=tee-sys -vv ./tests/kernel/wave/

      - name: Test TKW runtime related stack on amdgpu
        if: ${{ !cancelled() }}
        run: |
          export WAVE_CACHE_DIR=$PWD/.wave
          rm -rf ./.wave
          nproc
          WAVE_CACHE_ON=1 pytest --timeout=300 --capture=tee-sys -vv --run-e2e --durations=100 ./tests/kernel/wave/runtime

      - name: Run e2e tests on AMD GPU
        if: ${{ (github.event_name == 'pull_request') && !cancelled() }}
        run: |
          WAVE_CACHE_ON=0 pytest -n 1 --timeout=300 --capture=tee-sys -vv --run-e2e --durations=100 ./tests/kernel/wave/

      - name: Run expensive e2e tests on AMD GPU
        if: ${{ (github.event_name != 'pull_request') && !cancelled() }}
        run: |
          WAVE_CACHE_ON=0 pytest -n 1 --timeout=600 --capture=tee-sys -vv --run-e2e --run-expensive-tests --durations=100 ./tests/kernel/wave/

      - name: Run LIT tests
        if: ${{ !cancelled() }}
        run: |
          lit lit_tests/ -v
